### ISSUE TITLE
Add transition to mousewheel scale

### ISSUE THREAD

**Issue by skyfighteer** [rokobuljan/pan-zoom-area#1]
Would it be possible to add transition to the scale?

Thank you

**Comment by rokobuljan** [comment]
@skyfighteer Thank you for the suggestion.
I was thinking about that but had no time to properly implement. 

The simplest solution I can see so far would be to dynamically set a transition like i.e:

zoompan.js:~383

```js
this.elCanvas.style.transition = "0.3s";
this.elCanvas.addEventListener("transitionend", () => {
  // Reset to 0 so further panning will not be affected
  this.elCanvas.style.transition = "0s";
}, {once: true});
```
That's basically it but it's not yet portable. The above has to be performed only on mousewheel, not i.e: on touch-pinch since in that case the change in scale should be instantaneous.

What should be also added:

- A user-option like `wheelTransition: 0.3,`  
- Update the scaleWheel() method to infer into the logic that a physical mouse wheel was used. (That's in order to distinguish pinch scaling from mouse wheel scaling)

Will consider adding this shortly, after I finish implementing the pinch-scale plugin.

**Comment by skyfighteer** [comment]
I am glad you want to maintain this project!

Here is a reference for what I want from what I believe to be the best image viewer currently. However, your implementation will be far better and more modern, since this uses the old school width-height method.
https://github.com/s-yadav/iv-viewer
